# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/sibur/iiot/iiot_common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/sibur/iiot/iiot_common.proto',
  package='protos.sibur.iiot',
  syntax='proto3',
  serialized_options=b'Z\004iiot',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#protos/sibur/iiot/iiot_common.proto\x12\x11protos.sibur.iiot\"p\n\x0b\x43ommonError\x12*\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1c.protos.sibur.iiot.ErrorCode\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x0e\n\x06module\x18\x03 \x01(\t\x12\x0e\n\x06method\x18\x04 \x01(\t\"B\n\x0e\x44\x65viceFeatures\x12\x30\n\x06rossma\x18\x01 \x01(\x0b\x32 .protos.sibur.iiot.RossmaFeature\"\x1e\n\rRossmaFeature\x12\r\n\x05ports\x18\x01 \x03(\x05\"\xaa\x01\n\x12\x46\x65\x61tureCurrentLoop\x12\x41\n\x06rossma\x18\x01 \x03(\x0b\x32\x31.protos.sibur.iiot.FeatureCurrentLoop.RossmaEntry\x1aQ\n\x0bRossmaEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".protos.sibur.iiot.RossmaInterface:\x02\x38\x01\"\x93\x01\n\x0fRossmaInterface\x12\x34\n\x04reed\x18\x01 \x01(\x0b\x32$.protos.sibur.iiot.ReedSwitchChannelH\x00\x12=\n\x0c\x63urrent_loop\x18\x02 \x01(\x0b\x32%.protos.sibur.iiot.CurrentLoopChannelH\x00\x42\x0b\n\tinterface\"P\n\x12\x43urrentLoopChannel\x12\x13\n\x0bmeasurement\x18\x01 \x01(\t\x12\x11\n\tlow_value\x18\x02 \x01(\x05\x12\x12\n\nhigh_value\x18\x03 \x01(\x05\"\x13\n\x11ReedSwitchChannel\"2\n\x15\x44\x65viceActivationModes\x12\x0c\n\x04OTAA\x18\x01 \x01(\x08\x12\x0b\n\x03\x41\x42P\x18\x02 \x01(\x08*1\n\tErrorCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02*\x9f\x01\n\x0f\x44\x65viceEventType\x12\t\n\x05\x46IRST\x10\x00\x12\x17\n\x13\x43RITICAL_VALUE_HIGH\x10\x01\x12\x0f\n\x0bLOW_BATTERY\x10\x02\x12\x13\n\x0fLAST_CONNECTION\x10\x03\x12\x16\n\x12\x43RITICAL_VALUE_LOW\x10\x04\x12\x12\n\x0e\x43RITICAL_VALUE\x10\x05\x12\x16\n\x12SENSOR_MALFUNCTION\x10\x06*;\n\x0e\x41\x63tivationMode\x12\x16\n\x12\x41\x43TIVATION_UNKNOWN\x10\x00\x12\x08\n\x04OTAA\x10\x01\x12\x07\n\x03\x41\x42P\x10\x02\x42\x06Z\x04iiotb\x06proto3'
)

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='protos.sibur.iiot.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=750,
  serialized_end=799,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
_DEVICEEVENTTYPE = _descriptor.EnumDescriptor(
  name='DeviceEventType',
  full_name='protos.sibur.iiot.DeviceEventType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FIRST', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CRITICAL_VALUE_HIGH', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOW_BATTERY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LAST_CONNECTION', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CRITICAL_VALUE_LOW', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CRITICAL_VALUE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SENSOR_MALFUNCTION', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=802,
  serialized_end=961,
)
_sym_db.RegisterEnumDescriptor(_DEVICEEVENTTYPE)

DeviceEventType = enum_type_wrapper.EnumTypeWrapper(_DEVICEEVENTTYPE)
_ACTIVATIONMODE = _descriptor.EnumDescriptor(
  name='ActivationMode',
  full_name='protos.sibur.iiot.ActivationMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTIVATION_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTAA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ABP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=963,
  serialized_end=1022,
)
_sym_db.RegisterEnumDescriptor(_ACTIVATIONMODE)

ActivationMode = enum_type_wrapper.EnumTypeWrapper(_ACTIVATIONMODE)
UNKNOWN = 0
SUCCESS = 1
FAILED = 2
FIRST = 0
CRITICAL_VALUE_HIGH = 1
LOW_BATTERY = 2
LAST_CONNECTION = 3
CRITICAL_VALUE_LOW = 4
CRITICAL_VALUE = 5
SENSOR_MALFUNCTION = 6
ACTIVATION_UNKNOWN = 0
OTAA = 1
ABP = 2



_COMMONERROR = _descriptor.Descriptor(
  name='CommonError',
  full_name='protos.sibur.iiot.CommonError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protos.sibur.iiot.CommonError.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='protos.sibur.iiot.CommonError.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='module', full_name='protos.sibur.iiot.CommonError.module', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method', full_name='protos.sibur.iiot.CommonError.method', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=170,
)


_DEVICEFEATURES = _descriptor.Descriptor(
  name='DeviceFeatures',
  full_name='protos.sibur.iiot.DeviceFeatures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rossma', full_name='protos.sibur.iiot.DeviceFeatures.rossma', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=238,
)


_ROSSMAFEATURE = _descriptor.Descriptor(
  name='RossmaFeature',
  full_name='protos.sibur.iiot.RossmaFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ports', full_name='protos.sibur.iiot.RossmaFeature.ports', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=270,
)


_FEATURECURRENTLOOP_ROSSMAENTRY = _descriptor.Descriptor(
  name='RossmaEntry',
  full_name='protos.sibur.iiot.FeatureCurrentLoop.RossmaEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='protos.sibur.iiot.FeatureCurrentLoop.RossmaEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='protos.sibur.iiot.FeatureCurrentLoop.RossmaEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=443,
)

_FEATURECURRENTLOOP = _descriptor.Descriptor(
  name='FeatureCurrentLoop',
  full_name='protos.sibur.iiot.FeatureCurrentLoop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rossma', full_name='protos.sibur.iiot.FeatureCurrentLoop.rossma', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_FEATURECURRENTLOOP_ROSSMAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=443,
)


_ROSSMAINTERFACE = _descriptor.Descriptor(
  name='RossmaInterface',
  full_name='protos.sibur.iiot.RossmaInterface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reed', full_name='protos.sibur.iiot.RossmaInterface.reed', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_loop', full_name='protos.sibur.iiot.RossmaInterface.current_loop', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='interface', full_name='protos.sibur.iiot.RossmaInterface.interface',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=446,
  serialized_end=593,
)


_CURRENTLOOPCHANNEL = _descriptor.Descriptor(
  name='CurrentLoopChannel',
  full_name='protos.sibur.iiot.CurrentLoopChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='measurement', full_name='protos.sibur.iiot.CurrentLoopChannel.measurement', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='low_value', full_name='protos.sibur.iiot.CurrentLoopChannel.low_value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high_value', full_name='protos.sibur.iiot.CurrentLoopChannel.high_value', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=675,
)


_REEDSWITCHCHANNEL = _descriptor.Descriptor(
  name='ReedSwitchChannel',
  full_name='protos.sibur.iiot.ReedSwitchChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=677,
  serialized_end=696,
)


_DEVICEACTIVATIONMODES = _descriptor.Descriptor(
  name='DeviceActivationModes',
  full_name='protos.sibur.iiot.DeviceActivationModes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='OTAA', full_name='protos.sibur.iiot.DeviceActivationModes.OTAA', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ABP', full_name='protos.sibur.iiot.DeviceActivationModes.ABP', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=698,
  serialized_end=748,
)

_COMMONERROR.fields_by_name['code'].enum_type = _ERRORCODE
_DEVICEFEATURES.fields_by_name['rossma'].message_type = _ROSSMAFEATURE
_FEATURECURRENTLOOP_ROSSMAENTRY.fields_by_name['value'].message_type = _ROSSMAINTERFACE
_FEATURECURRENTLOOP_ROSSMAENTRY.containing_type = _FEATURECURRENTLOOP
_FEATURECURRENTLOOP.fields_by_name['rossma'].message_type = _FEATURECURRENTLOOP_ROSSMAENTRY
_ROSSMAINTERFACE.fields_by_name['reed'].message_type = _REEDSWITCHCHANNEL
_ROSSMAINTERFACE.fields_by_name['current_loop'].message_type = _CURRENTLOOPCHANNEL
_ROSSMAINTERFACE.oneofs_by_name['interface'].fields.append(
  _ROSSMAINTERFACE.fields_by_name['reed'])
_ROSSMAINTERFACE.fields_by_name['reed'].containing_oneof = _ROSSMAINTERFACE.oneofs_by_name['interface']
_ROSSMAINTERFACE.oneofs_by_name['interface'].fields.append(
  _ROSSMAINTERFACE.fields_by_name['current_loop'])
_ROSSMAINTERFACE.fields_by_name['current_loop'].containing_oneof = _ROSSMAINTERFACE.oneofs_by_name['interface']
DESCRIPTOR.message_types_by_name['CommonError'] = _COMMONERROR
DESCRIPTOR.message_types_by_name['DeviceFeatures'] = _DEVICEFEATURES
DESCRIPTOR.message_types_by_name['RossmaFeature'] = _ROSSMAFEATURE
DESCRIPTOR.message_types_by_name['FeatureCurrentLoop'] = _FEATURECURRENTLOOP
DESCRIPTOR.message_types_by_name['RossmaInterface'] = _ROSSMAINTERFACE
DESCRIPTOR.message_types_by_name['CurrentLoopChannel'] = _CURRENTLOOPCHANNEL
DESCRIPTOR.message_types_by_name['ReedSwitchChannel'] = _REEDSWITCHCHANNEL
DESCRIPTOR.message_types_by_name['DeviceActivationModes'] = _DEVICEACTIVATIONMODES
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
DESCRIPTOR.enum_types_by_name['DeviceEventType'] = _DEVICEEVENTTYPE
DESCRIPTOR.enum_types_by_name['ActivationMode'] = _ACTIVATIONMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonError = _reflection.GeneratedProtocolMessageType('CommonError', (_message.Message,), {
  'DESCRIPTOR' : _COMMONERROR,
  '__module__' : 'protos.sibur.iiot.iiot_common_pb2'
  # @@protoc_insertion_point(class_scope:protos.sibur.iiot.CommonError)
  })
_sym_db.RegisterMessage(CommonError)

DeviceFeatures = _reflection.GeneratedProtocolMessageType('DeviceFeatures', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEFEATURES,
  '__module__' : 'protos.sibur.iiot.iiot_common_pb2'
  # @@protoc_insertion_point(class_scope:protos.sibur.iiot.DeviceFeatures)
  })
_sym_db.RegisterMessage(DeviceFeatures)

RossmaFeature = _reflection.GeneratedProtocolMessageType('RossmaFeature', (_message.Message,), {
  'DESCRIPTOR' : _ROSSMAFEATURE,
  '__module__' : 'protos.sibur.iiot.iiot_common_pb2'
  # @@protoc_insertion_point(class_scope:protos.sibur.iiot.RossmaFeature)
  })
_sym_db.RegisterMessage(RossmaFeature)

FeatureCurrentLoop = _reflection.GeneratedProtocolMessageType('FeatureCurrentLoop', (_message.Message,), {

  'RossmaEntry' : _reflection.GeneratedProtocolMessageType('RossmaEntry', (_message.Message,), {
    'DESCRIPTOR' : _FEATURECURRENTLOOP_ROSSMAENTRY,
    '__module__' : 'protos.sibur.iiot.iiot_common_pb2'
    # @@protoc_insertion_point(class_scope:protos.sibur.iiot.FeatureCurrentLoop.RossmaEntry)
    })
  ,
  'DESCRIPTOR' : _FEATURECURRENTLOOP,
  '__module__' : 'protos.sibur.iiot.iiot_common_pb2'
  # @@protoc_insertion_point(class_scope:protos.sibur.iiot.FeatureCurrentLoop)
  })
_sym_db.RegisterMessage(FeatureCurrentLoop)
_sym_db.RegisterMessage(FeatureCurrentLoop.RossmaEntry)

RossmaInterface = _reflection.GeneratedProtocolMessageType('RossmaInterface', (_message.Message,), {
  'DESCRIPTOR' : _ROSSMAINTERFACE,
  '__module__' : 'protos.sibur.iiot.iiot_common_pb2'
  # @@protoc_insertion_point(class_scope:protos.sibur.iiot.RossmaInterface)
  })
_sym_db.RegisterMessage(RossmaInterface)

CurrentLoopChannel = _reflection.GeneratedProtocolMessageType('CurrentLoopChannel', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTLOOPCHANNEL,
  '__module__' : 'protos.sibur.iiot.iiot_common_pb2'
  # @@protoc_insertion_point(class_scope:protos.sibur.iiot.CurrentLoopChannel)
  })
_sym_db.RegisterMessage(CurrentLoopChannel)

ReedSwitchChannel = _reflection.GeneratedProtocolMessageType('ReedSwitchChannel', (_message.Message,), {
  'DESCRIPTOR' : _REEDSWITCHCHANNEL,
  '__module__' : 'protos.sibur.iiot.iiot_common_pb2'
  # @@protoc_insertion_point(class_scope:protos.sibur.iiot.ReedSwitchChannel)
  })
_sym_db.RegisterMessage(ReedSwitchChannel)

DeviceActivationModes = _reflection.GeneratedProtocolMessageType('DeviceActivationModes', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEACTIVATIONMODES,
  '__module__' : 'protos.sibur.iiot.iiot_common_pb2'
  # @@protoc_insertion_point(class_scope:protos.sibur.iiot.DeviceActivationModes)
  })
_sym_db.RegisterMessage(DeviceActivationModes)


DESCRIPTOR._options = None
_FEATURECURRENTLOOP_ROSSMAENTRY._options = None
# @@protoc_insertion_point(module_scope)
