# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protos.sibur.iiot import iiot_device_pb2 as protos_dot_sibur_dot_iiot_dot_iiot__device__pb2


class IotDeviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getDeviceList = channel.unary_unary(
                '/protos.sibur.iiot.IotDevice/getDeviceList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceListResponse.FromString,
                )
        self.getDeviceInfo = channel.unary_unary(
                '/protos.sibur.iiot.IotDevice/getDeviceInfo',
                request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceDataRequest.SerializeToString,
                response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceDataResponse.FromString,
                )
        self.getDeviceHistory = channel.unary_unary(
                '/protos.sibur.iiot.IotDevice/getDeviceHistory',
                request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceHistoryRequest.SerializeToString,
                response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceHistoryResponse.FromString,
                )
        self.createDevice = channel.unary_unary(
                '/protos.sibur.iiot.IotDevice/createDevice',
                request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.CreateDeviceRequest.SerializeToString,
                response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.CreateDeviceResponse.FromString,
                )
        self.deleteDevice = channel.unary_unary(
                '/protos.sibur.iiot.IotDevice/deleteDevice',
                request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeleteDeviceRequest.SerializeToString,
                response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeleteDeviceResponse.FromString,
                )
        self.updateDevice = channel.unary_unary(
                '/protos.sibur.iiot.IotDevice/updateDevice',
                request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.UpdateDeviceRequest.SerializeToString,
                response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.UpdateDeviceResponse.FromString,
                )
        self.sendDeviceConfiguration = channel.unary_unary(
                '/protos.sibur.iiot.IotDevice/sendDeviceConfiguration',
                request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceConfigurationRequest.SerializeToString,
                response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceConfigurationResponse.FromString,
                )
        self.sendEvents = channel.unary_unary(
                '/protos.sibur.iiot.IotDevice/sendEvents',
                request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.ServiceEventsRequest.SerializeToString,
                response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.ServiceEventsResponse.FromString,
                )
        self.getKeys = channel.unary_unary(
                '/protos.sibur.iiot.IotDevice/getKeys',
                request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.GetKeysRequest.SerializeToString,
                response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.GetKeysResponse.FromString,
                )
        self.changeDeviceType = channel.unary_unary(
                '/protos.sibur.iiot.IotDevice/changeDeviceType',
                request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.ChangeTypeRequest.SerializeToString,
                response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.ChangeTypeResponse.FromString,
                )


class IotDeviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getDeviceList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDeviceInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDeviceHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendDeviceConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def changeDeviceType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IotDeviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getDeviceList': grpc.unary_unary_rpc_method_handler(
                    servicer.getDeviceList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceListResponse.SerializeToString,
            ),
            'getDeviceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.getDeviceInfo,
                    request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceDataRequest.FromString,
                    response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceDataResponse.SerializeToString,
            ),
            'getDeviceHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.getDeviceHistory,
                    request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceHistoryRequest.FromString,
                    response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceHistoryResponse.SerializeToString,
            ),
            'createDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.createDevice,
                    request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.CreateDeviceRequest.FromString,
                    response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.CreateDeviceResponse.SerializeToString,
            ),
            'deleteDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteDevice,
                    request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeleteDeviceRequest.FromString,
                    response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeleteDeviceResponse.SerializeToString,
            ),
            'updateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.updateDevice,
                    request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.UpdateDeviceRequest.FromString,
                    response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.UpdateDeviceResponse.SerializeToString,
            ),
            'sendDeviceConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.sendDeviceConfiguration,
                    request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceConfigurationRequest.FromString,
                    response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceConfigurationResponse.SerializeToString,
            ),
            'sendEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.sendEvents,
                    request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.ServiceEventsRequest.FromString,
                    response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.ServiceEventsResponse.SerializeToString,
            ),
            'getKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.getKeys,
                    request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.GetKeysRequest.FromString,
                    response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.GetKeysResponse.SerializeToString,
            ),
            'changeDeviceType': grpc.unary_unary_rpc_method_handler(
                    servicer.changeDeviceType,
                    request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.ChangeTypeRequest.FromString,
                    response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.ChangeTypeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.sibur.iiot.IotDevice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IotDevice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getDeviceList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.sibur.iiot.IotDevice/getDeviceList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getDeviceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.sibur.iiot.IotDevice/getDeviceInfo',
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceDataRequest.SerializeToString,
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getDeviceHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.sibur.iiot.IotDevice/getDeviceHistory',
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceHistoryRequest.SerializeToString,
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.sibur.iiot.IotDevice/createDevice',
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.CreateDeviceRequest.SerializeToString,
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.CreateDeviceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.sibur.iiot.IotDevice/deleteDevice',
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeleteDeviceRequest.SerializeToString,
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeleteDeviceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.sibur.iiot.IotDevice/updateDevice',
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.UpdateDeviceRequest.SerializeToString,
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.UpdateDeviceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendDeviceConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.sibur.iiot.IotDevice/sendDeviceConfiguration',
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceConfigurationRequest.SerializeToString,
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceConfigurationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.sibur.iiot.IotDevice/sendEvents',
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.ServiceEventsRequest.SerializeToString,
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.ServiceEventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.sibur.iiot.IotDevice/getKeys',
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.GetKeysRequest.SerializeToString,
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.GetKeysResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def changeDeviceType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.sibur.iiot.IotDevice/changeDeviceType',
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.ChangeTypeRequest.SerializeToString,
            protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.ChangeTypeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
